/**
 * GitHub Pages Export API Route
 *
 * POST /api/v1/export/github - Export portfolio to GitHub Pages
 *
 * Request body:
 * {
 *   portfolioId: string     - Portfolio ID to export
 *   repoName?: string       - Custom repository name (default: 'portfolio')
 *   customDomain?: string   - Custom domain for CNAME
 *   isPrivate?: boolean     - Whether the repo should be private
 *   githubToken: string     - GitHub OAuth access token
 * }
 */

import { getDefaultTheme, getTheme } from '@/components/portfolio-themes/registry'
import { requireAuth } from '@/lib/api/auth-middleware'
import { rateLimitConfigs, withRateLimit } from '@/lib/api/rate-limit'
import { ApiError, withApiHandler } from '@/lib/api/route-handler'
import type { ExportData } from '@/lib/export'
import { generateStaticSite, validateExportData } from '@/lib/export'
import { GitHubClient, deployToGitHubPages, ensurePortfolioRepo } from '@/lib/github'
import { queries } from '@/lib/supabase/queries'
import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

// Request validation schema
const exportGitHubSchema = z.object({
  portfolioId: z.string().uuid('Invalid portfolio ID'),
  repoName: z
    .string()
    .min(1)
    .max(100)
    .regex(/^[a-zA-Z0-9_-]+$/, 'Invalid repo name')
    .optional()
    .default('portfolio'),
  customDomain: z.string().optional(),
  isPrivate: z.boolean().optional().default(false),
  githubToken: z.string().min(1, 'GitHub token is required'),
})

export const POST = withRateLimit(
  withApiHandler(async (request: NextRequest) => {
    const { user, supabase } = await requireAuth(request)

    // Parse and validate request body
    const json = await request.json()
    const parseResult = exportGitHubSchema.safeParse(json)

    if (!parseResult.success) {
      throw new ApiError(parseResult.error.issues.map((e) => e.message).join(', '), 400)
    }

    const { portfolioId, repoName, customDomain, isPrivate, githubToken } = parseResult.data

    // 1. Fetch portfolio data using typed query helper
    const { data: portfolio, error: portfolioError } = await queries.portfolios.getById(
      supabase,
      portfolioId
    )

    if (portfolioError || !portfolio) {
      throw new ApiError('Portfolio not found', 404)
    }

    // 2. Fetch portfolio sections using typed query helper
    const { data: sections, error: sectionsError } = await queries.sections.listByPortfolio(
      supabase,
      portfolioId
    )

    if (sectionsError) {
      throw new ApiError('Failed to fetch portfolio sections', 500)
    }

    // 3. Get theme
    const theme = getTheme(portfolio.theme || 'light-blue') || getDefaultTheme()

    // 4. Prepare export data
    const exportData: ExportData = {
      portfolio,
      sections: sections || [],
      theme,
      templateLayout: portfolio.template || 'single-column',
    }

    // 5. Validate export data
    const validation = validateExportData(exportData)
    if (!validation.valid) {
      throw new ApiError(`Invalid export data: ${validation.errors.join(', ')}`, 400)
    }

    // 6. Initialize GitHub client
    const githubClient = new GitHubClient({ accessToken: githubToken })

    // 7. Ensure repository exists
    let repoInfo
    try {
      repoInfo = await ensurePortfolioRepo(githubClient, {
        repoName,
        description: portfolio.description || 'Portfolio generated by Portfolio Forge',
        isPrivate,
      })
    } catch (error) {
      if (error instanceof Error) {
        throw new ApiError(`GitHub error: ${error.message}`, 400)
      }
      throw new ApiError('Failed to create GitHub repository', 500)
    }

    // 8. Generate static site
    const baseUrl = customDomain
      ? `https://${customDomain}`
      : `https://${repoInfo.owner}.github.io/${repoInfo.repo}`

    const bundle = await generateStaticSite({
      config: {
        portfolioId,
        platform: 'github_pages',
        customDomain,
        repoName,
        minify: true,
        generateSitemap: true,
        generateRobots: true,
      },
      data: exportData,
      baseUrl,
    })

    // 9. Deploy to GitHub Pages
    let deployResult
    try {
      deployResult = await deployToGitHubPages(githubClient, bundle, {
        owner: repoInfo.owner,
        repo: repoInfo.repo,
        branch: repoInfo.defaultBranch,
        message: `Deploy portfolio: ${portfolio.title}`,
      })
    } catch (error) {
      if (error instanceof Error) {
        throw new ApiError(`Deployment failed: ${error.message}`, 500)
      }
      throw new ApiError('Failed to deploy to GitHub Pages', 500)
    }

    // 10. Save export record to database (optional - if table exists)
    try {
      await (supabase.from('portfolio_exports') as ReturnType<typeof supabase.from>).upsert(
        {
          portfolio_id: portfolioId,
          user_id: user.id,
          export_type: 'github_pages',
          github_repo_url: repoInfo.htmlUrl,
          github_pages_url: deployResult.pagesUrl,
          last_deployed_at: new Date().toISOString(),
          last_commit_sha: deployResult.commitSha,
          status: 'deployed',
        },
        {
          onConflict: 'portfolio_id,export_type',
        }
      )
    } catch {
      // Table might not exist yet - ignore
    }

    return NextResponse.json({
      success: true,
      export: {
        portfolioId,
        repoUrl: repoInfo.htmlUrl,
        pagesUrl: deployResult.pagesUrl,
        commitSha: deployResult.commitSha,
        branch: repoInfo.defaultBranch,
        generatedAt: bundle.generatedAt.toISOString(),
        filesCount: bundle.files.length,
        totalSize: bundle.totalSize,
      },
    })
  }),
  rateLimitConfigs.export
)
